// Generated by CoffeeScript 1.6.3
(function() {
  var checkArgs, log, packageinf, program, _;

  program = require('commander');

  packageinf = require('../package.json');

  log = require('npmlog');

  _ = require('lodash');

  log.info('version', packageinf.version);

  checkArgs = function() {
    var jobs;
    program.dry = !!program.dry;
    jobs = Number(program.jobs);
    if (_.isNaN(jobs) || jobs < 1 || (("" + (parseInt(program.jobs))) !== program.jobs)) {
      log.error('args', "Invalid concurrency: " + program.jobs);
      return process.exit(1);
    }
  };

  program.version(packageinf.version).option('-d, --dry', 'No renaming, just output. ', false).option('-j, --jobs [limit]', 'Concurrency', "5");

  program.command('tag [dir]').description('Tag images from pixiv.').action(function(env) {
    var dir;
    checkArgs();
    dir = env || process.cwd();
    return require('./pixiv.comm')(dir, program, log);
  });

  program.parse(process.argv);

}).call(this);

//# sourceMappingURL=index.map
