// Generated by CoffeeScript 1.6.3
(function() {
  var Q, cheerio, request, _;

  request = require('superagent');

  _ = require('lodash');

  Q = require('q');

  cheerio = require('cheerio');

  module.exports = function(id) {
    var agent;
    agent = request.get(['http://www.pixiv.net/member_illust.php?mode=medium&illust_id=', id].join('')).set('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36');
    return Q.ninvoke(agent, 'end').then(function(rep) {
      var $, e, info, tags, user, userinf;
      if (rep.statusCode !== 200) {
        throw new Error("Server response: " + rep.statusCode + ".");
      }
      $ = cheerio.load(rep.text);
      info = {
        work_id: id
      };
      try {
        userinf = $('.userdata');
        info.title = userinf.children('.title').text();
        user = userinf.children('.name').children('a');
        info.user_id = _.last(user.attr('href').split('?id='));
        info.user = user.text();
        info.tags = tags = [];
        $('#tag_area').find('.tag').each(function(index, elem) {
          return tags.push($(this).children('a.text').text().trim());
        });
      } catch (_error) {
        e = _error;
        console.dir(e);
        throw new Error("Invalid response: " + e + ".");
      }
      return info;
    });
  };

}).call(this);

//# sourceMappingURL=pixiv.fetch.map
